---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: CustomizeRequest
    inherits: 
    description: 
  fields:
  - common_meth1:
      value: common_CustomizeRequest
  - vmware_meth1:
      value: vmware_CustomizeRequest
  - redhat_meth1:
      value: redhat_CustomizeRequest
  - microsoft_meth1:
      value: microsoft_CusotmizeRequest
